// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosqueManagement.Data;

#nullable disable

namespace MosqueManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230416074953_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MosqueManagement.Models.Class", b =>
                {
                    b.Property<int>("formId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("formId"));

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("approval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvalMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvalYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("paymentId")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("serviceId")
                        .HasColumnType("int");

                    b.HasKey("formId");

                    b.HasIndex("Userid");

                    b.HasIndex("paymentId");

                    b.HasIndex("serviceId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("MosqueManagement.Models.Donation", b =>
                {
                    b.Property<int>("donationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("donationId"));

                    b.Property<double>("donationAmount")
                        .HasColumnType("float");

                    b.Property<string>("donationSuccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("donationId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("MosqueManagement.Models.HumanResource", b =>
                {
                    b.Property<int>("positionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("positionId"));

                    b.Property<string>("positionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("positionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("serviceId")
                        .HasColumnType("int");

                    b.Property<string>("staffContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("positionId");

                    b.HasIndex("serviceId");

                    b.ToTable("HumanResources");
                });

            modelBuilder.Entity("MosqueManagement.Models.Market", b =>
                {
                    b.Property<int>("marketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("marketId"));

                    b.Property<string>("marketContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marketDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marketName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("marketId");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("MosqueManagement.Models.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentId"));

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<string>("paymentSuccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentId");

                    b.HasIndex("Userid");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MosqueManagement.Models.Rental", b =>
                {
                    b.Property<int>("formId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("formId"));

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("approval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvalMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvalYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("paymentId")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("serviceId")
                        .HasColumnType("int");

                    b.Property<string>("startDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("formId");

                    b.HasIndex("Userid");

                    b.HasIndex("paymentId");

                    b.HasIndex("serviceId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("MosqueManagement.Models.Schedule", b =>
                {
                    b.Property<int>("scheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("scheduleId"));

                    b.Property<int?>("ClassformId")
                        .HasColumnType("int");

                    b.Property<int?>("RentalformId")
                        .HasColumnType("int");

                    b.Property<int?>("SocialformId")
                        .HasColumnType("int");

                    b.Property<string>("occupied")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("scheduleId");

                    b.HasIndex("ClassformId");

                    b.HasIndex("RentalformId");

                    b.HasIndex("SocialformId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("MosqueManagement.Models.Service", b =>
                {
                    b.Property<int>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceId"));

                    b.Property<int>("serviceCategory")
                        .HasColumnType("int");

                    b.Property<string>("serviceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceEquipments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("servicePrice")
                        .HasColumnType("float");

                    b.HasKey("serviceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MosqueManagement.Models.Social", b =>
                {
                    b.Property<int>("formId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("formId"));

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("approval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvalMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvalYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("paymentId")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("serviceId")
                        .HasColumnType("int");

                    b.HasKey("formId");

                    b.HasIndex("Userid");

                    b.HasIndex("paymentId");

                    b.HasIndex("serviceId");

                    b.ToTable("Socials");
                });

            modelBuilder.Entity("MosqueManagement.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MosqueManagement.Models.Class", b =>
                {
                    b.HasOne("MosqueManagement.Models.User", null)
                        .WithMany("Classs")
                        .HasForeignKey("Userid");

                    b.HasOne("MosqueManagement.Models.Payment", null)
                        .WithMany("Classs")
                        .HasForeignKey("paymentId");

                    b.HasOne("MosqueManagement.Models.Service", null)
                        .WithMany("Classs")
                        .HasForeignKey("serviceId");
                });

            modelBuilder.Entity("MosqueManagement.Models.HumanResource", b =>
                {
                    b.HasOne("MosqueManagement.Models.Service", null)
                        .WithMany("HumanResources")
                        .HasForeignKey("serviceId");
                });

            modelBuilder.Entity("MosqueManagement.Models.Payment", b =>
                {
                    b.HasOne("MosqueManagement.Models.User", null)
                        .WithMany("Payments")
                        .HasForeignKey("Userid");
                });

            modelBuilder.Entity("MosqueManagement.Models.Rental", b =>
                {
                    b.HasOne("MosqueManagement.Models.User", null)
                        .WithMany("Rentals")
                        .HasForeignKey("Userid");

                    b.HasOne("MosqueManagement.Models.Payment", null)
                        .WithMany("Rentals")
                        .HasForeignKey("paymentId");

                    b.HasOne("MosqueManagement.Models.Service", null)
                        .WithMany("Rentals")
                        .HasForeignKey("serviceId");
                });

            modelBuilder.Entity("MosqueManagement.Models.Schedule", b =>
                {
                    b.HasOne("MosqueManagement.Models.Class", null)
                        .WithMany("Schedules")
                        .HasForeignKey("ClassformId");

                    b.HasOne("MosqueManagement.Models.Rental", null)
                        .WithMany("Schedules")
                        .HasForeignKey("RentalformId");

                    b.HasOne("MosqueManagement.Models.Social", null)
                        .WithMany("Schedules")
                        .HasForeignKey("SocialformId");
                });

            modelBuilder.Entity("MosqueManagement.Models.Social", b =>
                {
                    b.HasOne("MosqueManagement.Models.User", null)
                        .WithMany("Socials")
                        .HasForeignKey("Userid");

                    b.HasOne("MosqueManagement.Models.Payment", null)
                        .WithMany("Socials")
                        .HasForeignKey("paymentId");

                    b.HasOne("MosqueManagement.Models.Service", null)
                        .WithMany("Socials")
                        .HasForeignKey("serviceId");
                });

            modelBuilder.Entity("MosqueManagement.Models.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MosqueManagement.Models.Payment", b =>
                {
                    b.Navigation("Classs");

                    b.Navigation("Rentals");

                    b.Navigation("Socials");
                });

            modelBuilder.Entity("MosqueManagement.Models.Rental", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MosqueManagement.Models.Service", b =>
                {
                    b.Navigation("Classs");

                    b.Navigation("HumanResources");

                    b.Navigation("Rentals");

                    b.Navigation("Socials");
                });

            modelBuilder.Entity("MosqueManagement.Models.Social", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MosqueManagement.Models.User", b =>
                {
                    b.Navigation("Classs");

                    b.Navigation("Payments");

                    b.Navigation("Rentals");

                    b.Navigation("Socials");
                });
#pragma warning restore 612, 618
        }
    }
}
